AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'


Resources:

  Layer16:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: layer-16
      Description: Lambda layer 16
      ContentUri: ./opencv4nodejs-layer-node16.zip
  Test16:
      Type: 'AWS::Serverless::Function'
      Properties:
        Runtime: nodejs16.x
        Layers:
          - !Ref Layer16
        FunctionName: test16
        Handler: handler.handler
  Layer18:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: layer-18
      Description: Lambda layer 18
      ContentUri: ./opencv4nodejs-layer-node18.zip
  Test16:
      Type: 'AWS::Serverless::Function'
      Properties:
        Runtime: nodejs18.x
        Layers:
          - !Ref Layer18
        FunctionName: test18
        Handler: handler.handler