name: Semantic release

on:
  push

env:
  OPENCV4NODEJS_AUTOBUILD_OPENCV_VERSION: 4.6.0

jobs:
  build:
    name: Build and Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: aws-actions/setup-sam@v2
      - name: Build project 
        run: node ./bin/package-layers.js --node-version 18 --opencv-version ${{ env.OPENCV4NODEJS_AUTOBUILD_OPENCV_VERSION }}
          
      - name: Test packages
        run: node ./bin/test-layers.js --node-version 18 --opencv-version ${{ env.OPENCV4NODEJS_AUTOBUILD_OPENCV_VERSION }}
          
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}